<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1f2937; font-size: 12px; margin: 0; padding: 32px; }
        .header { display: flex; justify-content: space-between; border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
        .brand { font-size: 22px; font-weight: bold; color: #2563eb; }
        .muted { color: #6b7280; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        .meta-table { width: 100%; margin-bottom: 24px; }
        .meta-table td { vertical-align: top; padding: 2px 0; }
        .label { color: #6b7280; width: 120px; }
        table.lines { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.lines th { text-align: left; background: #f3f4f6; padding: 8px; font-size: 11px; text-transform: uppercase; color: #6b7280; }
        table.lines td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
        .right { text-align: right; }
        .total-row td { font-weight: bold; font-size: 14px; border-top: 2px solid #2563eb; }
        .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; background: #eff6ff; color: #2563eb; font-size: 11px; }
        .footer { margin-top: 40px; color: #9ca3af; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="brand">PubAds</div>
            <div class="muted">Advertising Spaces Marketplace</div>
        </div>
        <div style="text-align:right;">
            <h1>INVOICE</h1>
            <div class="muted">{{ $invoice->invoice_number }}</div>
            <div class="badge">{{ ucfirst($invoice->status) }}</div>
        </div>
    </div>

    <table class="meta-table">
        <tr>
            <td class="label">Billed to</td>
            <td>
                <strong>{{ $client->company_name ?: $client->name }}</strong><br>
                {{ $client->email }}@if($client->address)<br>{{ $client->address }}@endif
            </td>
            <td class="label">Issued</td>
            <td>{{ optional($invoice->issued_at)->format('M d, Y') ?: '—' }}</td>
        </tr>
        <tr>
            <td class="label">Campaign</td>
            <td>{{ $invoice->campaign->name }}</td>
            <td class="label">Due</td>
            <td>{{ optional($invoice->due_at)->format('M d, Y') ?: '—' }}</td>
        </tr>
    </table>

    <table class="lines">
        <thead>
            <tr>
                <th>Adset</th>
                <th>Ad</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @php $hasLines = false; @endphp
            @foreach($invoice->campaign->adsets as $adset)
                @foreach($adset->ads as $ad)
                    @php $hasLines = true; @endphp
                    <tr>
                        <td>{{ $adset->name }}</td>
                        <td>{{ $ad->name }}</td>
                        <td class="right">@if(!is_null($ad->price))${{ number_format((float) $ad->price, 2) }}@else—@endif</td>
                    </tr>
                @endforeach
            @endforeach
            @unless($hasLines)
                <tr>
                    <td colspan="2">Campaign total ({{ $invoice->campaign->name }})</td>
                    <td class="right">${{ number_format((float) $invoice->total_amount, 2) }}</td>
                </tr>
            @endunless
            <tr class="total-row">
                <td colspan="2">Total</td>
                <td class="right">${{ number_format((float) $invoice->total_amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by PubAds — this is a system-generated invoice. Payments are processed via the platform.
    </div>
</body>
</html>
